
const airlinesData = [
  {
    airline: "Hawaiian Airlines",
    flightNumber: "FIG4312",
    departure: "7:00 AM",
    arrival: "4:15 PM",
    duration: "16h 45m",
    price: "$503",
    tax: "$91",
    fee: "$30",
    totalPrice: "$624",
    travelType: "round trip",
    stop: {
      stopAmount: "1 stop",
      stopPlace: "HNL",
      stopTime: "2h 45m",
    },
  },
  {
    airline: "Japan Airlines",
    flightNumber: "FJA2412",
    departure: "7:35 AM",
    arrival: "12:15 PM",
    duration: "1h 22m",
    price: "$503",
    tax: "$91",
    fee: "$30",
    totalPrice: "$624",
    travelType: "round trip",
    stop: {
      stopAmount: "1 stop",
      stopPlace: "HKG",
      stopTime: "50m",
    },
  },
  {
    airline: "Hawaiian Airlines",
    flightNumber: "FIG4325",
    departure: "8:20 AM",
    arrival: "2:15 PM",
    duration: "18h 04m",
    price: "$503",
    tax: "$91",
    fee: "$30",
    totalPrice: "$624",
    travelType: "round trip",
    stop: {
      stopAmount: "1 stop",
      stopPlace: "PVG",
      stopTime: "1h 50m",
    },
  },
  {
    airline: "Delta",
    flightNumber: "FDE6512",
    departure: "9:47 AM",
    arrival: "4:15 PM",
    duration: "18h 52m",
    price: "$503",
    tax: "$91",
    fee: "$30",
    totalPrice: "$624",
    travelType: "round trip",
    stop: {
      stopAmount: "1 stop",
      stopPlace: "ICN",
      stopTime: "4h 05m",
    },
  },
  {
    airline: "Hawaiian Airlines",
    flightNumber: "FIG4345",
    departure: "11:15 AM",
    arrival: "7:45 PM",
    duration: "16h 05m",
    price: "$503",
    tax: "$91",
    fee: "$30",
    totalPrice: "$624",
    travelType: "round trip",
    stop: {
      stopAmount: "Nonstop",
      stopPlace: false,
      stopTime: false,
    },
  },
  {
    airline: "Hawaiian Airlines",
    flightNumber: "FIG4365",
    departure: "10:55 AM",
    arrival: "8:15 PM",
    duration: "15h 45m",
    price: "$503",
    tax: "$91",
    fee: "$30",
    totalPrice: "$624",
    travelType: "round trip",
    stop: {
      stopAmount: "Nonstop",
      stopPlace: false,
      stopTime: false,
    },
  },
  {
    airline: "Delta",
    flightNumber: "FDE6530",
    departure: "1:00 PM",
    arrival: "9:15 PM",
    duration: "18h 20m",
    price: "$503",
    tax: "$91",
    fee: "$30",
    totalPrice: "$624",
    travelType: "round trip",
    stop: {
      stopAmount: "1 stop",
      stopPlace: "ICN",
      stopTime: "4h 45m",
    },
  },
  {
    airline: "EVA Air",
    flightNumber: "FEV7512",
    departure: "2:15 PM",
    arrival: "11:15 PM",
    duration: "18h 55m",
    price: "$503",
    tax: "$91",
    fee: "$30",
    totalPrice: "$624",
    travelType: "round trip",
    stop: {
      stopAmount: "1 stop",
      stopPlace: "HNL",
      stopTime: "2h 45m",
    },
  },
];


export default airlinesData
